os: linux
language: dart

addons:
  apt:
    # Flutter dependencies
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid-fallback

before_install:
  - echo $TRAVIS_OS_NAME
  - echo ${HOME}
  - echo ${TRAVIS_BUILD_DIR}
  - git clone https://github.com/flutter/flutter.git -b master --depth 1 ${HOME}/flutter
  - ${HOME}/flutter/bin/flutter doctor -v
  - ${HOME}/flutter/bin/flutter pub global activate webdev
  - ${HOME}/flutter/bin/flutter packages get
  - ${HOME}/flutter/bin/flutter pub global run webdev build

script:
  - ${HOME}/.pub-cache/bin/webdev build

after_success:
  - echo "success"

after_failure:
  - echo "failure"
