os: linux
language: dart

addons:
  apt:
    # Flutter dependencies
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid-fallback

before_install:
  - echo $TRAVIS_OS_NAME
  - echo ${HOME}
  - echo ${TRAVIS_BUILD_DIR}
  - git clone https://github.com/flutter/flutter.git -b master ${HOME}/flutter
  - export PATH=$PATH:${HOME}/flutter/bin
  - flutter doctor -v
  - flutter packages get
  - flutter packages pub run build_runner build lib
  - flutter config --enable-web

script:
  - flutter build web --release

after_success:
  - echo "success"

after_failure:
  - echo "failure"
