name: cruzweb

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  clippy: ^1.0.0
  cruzawl:
    path: ./cruzawl
  cruzawl_ui:
    path: ./cruzawl-ui
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl_translation: ^0.17.1
  scoped_model: ^1.0.1
  sembast: ^2.0.1

dev_dependencies:
  # Enables the `pub run build_runner` command
  build_runner: ^1.6.5
  # Includes the JavaScript compilers
  build_web_compilers: ^2.1.5

dependency_overrides:
  intl: 0.16.0
